apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-container
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30203
  type: NodePort
