version: '3'

networks:
  monreseau:
    external: false

services:
  web:
    build: .
    container_name: monsiteweb
    volumes:
      - dj_postgresstatics:/app/static_assets/
      - dj_postgresmedias:/app/medias/
    depends_on:
      - db
    networks:
      - monreseau

  db:
    image: 'postgres:latest'
    container_name: monsitedb
    environment:  # Correction ici
      POSTGRES_PASSWORD: monpassword
    volumes:
      - pgdb:/var/lib/postgresql/data
    networks:
      - monreseau

  nginx:
    image: 'nginx:1.19-alpine'
    container_name: monsitenginx
    volumes:
      - dj_postgresstatics:/home/app/web/static_assets
      - dj_postgresmedias:/home/app/web/medias
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - monreseau
    ports:
      - '80:80'

volumes:  # Correction ici
  pgdb:
  dj_postgresstatics:
  dj_postgresmedias:
